repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.12
    hooks:
      - id: ruff
        args: ["--fix"]
        language_version: python3.11

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit
        args: ["-ll", "-iii"]
        language_version: python3.11

  # Statt mirrors-mypy:
  - repo: local
    hooks:
      - id: custom-mypy
        name: Run mypy with ignore-missing-imports
        entry: mypy --ignore-missing-imports
        language: system
        types: [python]
